name: Build & Publish

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: 22.21.0
  ENABLE_CACHE: yes
  NPM_VERSION: 11.5.2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Check if package.json version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: package.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: ${{ env.ENABLE_CACHE == 'yes' && 'npm' || '' }}

      - run: npm i -g npm@${{ env.NPM_VERSION }}

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.version }}
          release_name: v${{ steps.check.outputs.version }}
          draft: false
          prerelease: false

      - run: npm publish --access=public
        if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
